# Generated by Django 5.1.2 on 2024-11-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeorder",
            name="status",
            field=models.CharField(default="Executed", max_length=20),
        ),
    ]
