# Generated by Django 5.1.2 on 2024-11-17 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0002_tradeorder_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradeorder",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.CreateModel(
            name="TradesTaken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.CharField(blank=True, max_length=50)),
                ("exchange", models.CharField(blank=True, max_length=50)),
                ("trading_symbol", models.CharField(blank=True, max_length=50)),
                ("series", models.CharField(blank=True, max_length=10)),
                ("lot_size", models.IntegerField(blank=True)),
                ("quantity", models.IntegerField(blank=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=100)),
                ("trade_type", models.CharField(blank=True, max_length=10)),
                ("avg_price", models.FloatField(blank=True)),
                ("prctype", models.CharField(blank=True, max_length=10)),
                ("invested_coin", models.FloatField(blank=True)),
                ("profit_loss", models.FloatField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_type", models.CharField(blank=True, max_length=10)),
                ("quantity", models.IntegerField(blank=True)),
                ("trade_price", models.FloatField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trade_history",
                        to="trades.tradestaken",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClosedTrades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sell_quantity", models.IntegerField()),
                ("sell_price", models.FloatField()),
                ("sell_date", models.DateTimeField(auto_now_add=True)),
                ("profit_loss", models.FloatField()),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="closed_trades",
                        to="trades.tradestaken",
                    ),
                ),
            ],
        ),
    ]
