# Generated by Django 5.1.2 on 2024-11-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0003_alter_tradeorder_status_tradestaken_tradehistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradestaken",
            name="expiry_date",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tradestaken",
            name="option_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tradestaken",
            name="ssegment",
            field=models.CharField(default="EQ", max_length=100),
        ),
        migrations.AddField(
            model_name="tradestaken",
            name="ticker",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tradestaken",
            name="trade_status",
            field=models.CharField(default="incomplete", max_length=100, null=True),
        ),
    ]
