# Generated by Django 5.1.2 on 2024-11-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0004_tradestaken_expiry_date_tradestaken_option_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tradestaken",
            old_name="ssegment",
            new_name="segment",
        ),
    ]
