# Generated by Django 5.1.2 on 2024-11-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0005_rename_ssegment_tradestaken_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="closedtrades",
            name="profit_loss",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="tradestaken",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="tradestaken",
            name="profit_loss",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="tradestaken",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
