# Generated by Django 5.1.2 on 2024-11-20 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0006_alter_closedtrades_profit_loss_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tradestaken",
            old_name="profit_loss",
            new_name="margin_required",
        ),
    ]
