# Generated by Django 5.1.2 on 2024-12-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0008_marginlocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="closedtrades",
            name="avg_price",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="tradestaken",
            name="product_type",
            field=models.CharField(
                choices=[("delivery", "Delivery"), ("intraday", "Intraday")],
                default="Delivery",
                max_length=30,
            ),
        ),
    ]
