# Generated by Django 5.1.2 on 2024-12-16 05:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0009_closedtrades_avg_price_tradestaken_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="closedtrades",
            name="product_type",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
