# Generated by Django 5.1.2 on 2024-12-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0010_closedtrades_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradestaken",
            name="product_type",
            field=models.CharField(
                choices=[("Delivery", "Delivery"), ("Intraday", "Intraday")],
                default="Delivery",
                max_length=30,
            ),
        ),
    ]
