# Generated by Django 5.1.2 on 2024-12-17 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0011_alter_tradestaken_product_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LimitOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.CharField(blank=True, max_length=50)),
                ("exchange", models.CharField(blank=True, max_length=50)),
                ("trading_symbol", models.CharField(blank=True, max_length=50)),
                ("series", models.CharField(blank=True, max_length=10)),
                ("lot_size", models.IntegerField(blank=True)),
                ("quantity", models.IntegerField(blank=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=100)),
                ("expiry_date", models.CharField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("Delivery", "Delivery"), ("Intraday", "Intraday")],
                        default="Delivery",
                        max_length=30,
                    ),
                ),
                ("segment", models.CharField(default="EQ", max_length=100)),
                ("option_type", models.CharField(blank=True, max_length=20, null=True)),
                ("trade_type", models.CharField(blank=True, max_length=10)),
                ("avg_price", models.FloatField(blank=True)),
                ("prctype", models.CharField(blank=True, max_length=10)),
                ("invested_coin", models.FloatField(blank=True)),
                ("executed", models.BooleanField(default=False)),
                (
                    "trade_status",
                    models.CharField(default="incomplete", max_length=100, null=True),
                ),
                ("ticker", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
