# Generated by Django 5.1.2 on 2024-11-15 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradingInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_id", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=100)),
                ("trading_symbol", models.CharField(max_length=100)),
                ("series", models.CharField(max_length=10)),
                ("script_name", models.CharField(max_length=255)),
                ("ticker", models.CharField(max_length=50)),
                (
                    "expiry_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("option_type", models.CharField(blank=True, max_length=20, null=True)),
                ("segment", models.CharField(max_length=50)),
                ("lot_size", models.IntegerField()),
                ("tick_size", models.FloatField()),
                ("strike_price", models.FloatField(blank=True, null=True)),
                ("display_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                ("instrument_name", models.CharField(max_length=255)),
                ("isin_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruments",
                        to="instrument_master.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
