# Generated by Django 5.1.2 on 2024-11-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instrument_master", "0003_alter_tradinginstrument_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradinginstrument",
            name="expiry_date",
            field=models.CharField(blank=True, null=True),
        ),
    ]
