# Generated by Django 5.1.2 on 2024-11-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instrument_master", "0004_alter_tradinginstrument_expiry_date"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tradinginstrument",
            index=models.Index(
                fields=["exchange"], name="instrument__exchang_000a17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradinginstrument",
            index=models.Index(
                fields=["segment"], name="instrument__segment_18b8da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradinginstrument",
            index=models.Index(
                fields=["script_name"], name="instrument__script__e078f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradinginstrument",
            index=models.Index(
                fields=["exchange", "segment"], name="instrument__exchang_92deb2_idx"
            ),
        ),
    ]
