# Generated by Django 5.1.2 on 2024-12-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instrument_master", "0006_uploadedfile_error_message_uploadedfile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(default=None, upload_to="uploads/"),
        ),
    ]
