# Generated by Django 5.1.2 on 2024-12-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instrument_master", "0007_uploadedfile_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="file",
        ),
    ]
