# Generated by Django 5.1.2 on 2024-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "broadcast_token",
                    models.CharField(
                        blank=True,
                        help_text="Token used for broadcasting.",
                        max_length=1000,
                        null=True,
                        verbose_name="Broadcast Token",
                    ),
                ),
                (
                    "broadcast_userid",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="User ID associated with the broadcast token.",
                        max_length=20,
                        null=True,
                        verbose_name="Broadcast User ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
    ]
