# Generated by Django 5.1.2 on 2024-11-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_profile_last_updated_beetlecoins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beetlecoins",
            name="coins",
            field=models.PositiveIntegerField(default=1000000),
        ),
    ]
