# Generated by Django 5.1.2 on 2024-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_beetlecoins_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
