# Generated by Django 5.1.2 on 2024-11-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_profile_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beetlecoins",
            name="used_coins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
